version: "3.1"
services:
    www:
        container_name: cedadmision_apache
        restart: always
        build: .
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        container_name: cedadmision_bd
        restart: always
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: cedadmision
            MYSQL_USER: cedadmision
            MYSQL_PASSWORD: cedadmisionpassw
            MYSQL_ROOT_PASSWORD: cedadmisionpassw 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
