version: "3.1"
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
            - certs:/etc/nginx/certs:ro
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
            - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
            - certs:/etc/nginx/certs:rw
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
    db:
        container_name: cedadmision_bd
        restart: always
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: cedadmision
            MYSQL_USER: cedadmision
            MYSQL_PASSWORD: cedadmisionpassw
            MYSQL_ROOT_PASSWORD: cedadmisionpassw 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
    www:
        container_name: cedadmision_apache
        restart: always
        build: .
        expose:
            - "80"
        volumes:
            - ./www:/var/www/html/
        environment:
            - VIRTUAL_HOST=cedpdvbolivia.com,www.cedpdvbolivia.com
            - LETSENCRYPT_HOST=cedpdvbolivia.com,www.cedpdvbolivia.com
        depends_on:
            - db
            - nginx-proxy
            - letsencrypt
volumes:
    persistent:
    certs:
    html:
    vhostd:
